### ISSUE TITLE
MLflow configuration for GitLab

### ISSUE THREAD

**Issue by CGuichard** [csgroup-oss/sharinghub-server#7]
As of now, the mlflow configuration gives an URL to a MLflow SharingHub instance.
The config should be detailed slightly more, and add compatibility for GitLab Mlflow and simple MLflow.

Examples:

MLflow config:

```yaml
mlflow:
    type: mlflow
    url: https://sharinghub.example.com/mlflow
```

MLflow SharingHub config:

```yaml
mlflow:
    type: mlflow-sharinghub
    url: https://sharinghub.example.com/mlflow
```

GitLab MLflow config:

```yaml
mlflow:
    type: gitlab
    url: https://gitlab.example.com
```
